title: Tangible Math, Meaningful Code # your name (or website title) here
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
logo: "/images/blog_title.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ke Liu 
  <br><br>
  Quantitative Researcher, Math Enthusiast
  <br><br>
  <a href="https://www.linkedin.com/in/ke-liu-at-caltech/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
